CREATE TABLE PILOTO(
    ID_PILOTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50),
    AP_PA VARCHAR2(50),
    AP_MA VARCHAR2(50),
    ESCOLARIDAD VARCHAR2(50),
    SALUD VARCHAR2(50),
    CONSTRAINT PILOTOS_PK PRIMARY KEY(ID_PILOTO)
);

CREATE TABLE COHETES(
    ID_COHETE NUMBER NOT NULL,
    NOMBRE VARCHAR2(50),
    DESTINO VARCHAR2(50),
    TRIPULANTES NUMBER NOT NULL,
    COMBUSTIBLE NUMBER NOT NULL,
    PILOTO_ID NUMBER NOT NULL,
    CONSTRAINT COHETES_PK PRIMARY KEY(ID_COHETE),
    CONSTRAINT COHETES_PILOTOS_FK FOREIGN KEY(PILOTO_ID)
    REFERENCES PILOTO(ID_PILOTO)
);

DROP TABLE COHETES;

CREATE TABLE DESPEGUE(
    ID_DESPEGUE NUMBER NOT NULL,
    COHETE_ID NUMBER NOT NULL,
    FECHA_DESPEGUE DATE,
    CONSTRAINT DESPEGUES_PK PRIMARY KEY(ID_DESPEGUE),
    CONSTRAINT DESPEGUES_COHETES_FK FOREIGN KEY(COHETE_ID)
    REFERENCES COHETE(ID_COHETE)
);

DROP TABLE DESPEGUE;